### PR TITLE
Use message instead of raw _line output

### PR DESCRIPTION
**Pull request by schans**
Fix output for syslog tailing on the command line: https://github.com/logdna/logdna-cli/issues/19

### CODE REVIEW

**Comment by smusali** [comment]
Hey @schans, 

Sorry for late response!

For the sake of keeping all dependencies consistent, can you revert `package.json` back? I mean, updating the dependencies may cause the different kind of issues; so, in order to prevent that we try not to update it unless we urgently need it.

Thanks!

**Comment by smusali** [comment]
Hey @schans,

I have carefully investigated your suggested changes in this Pull Request. Unfortunately, we cannot use `line.message` for all lines considering not all `line` objects have `message` field. Instead, I have added `line.message || line._line` in #21; so, in that way, if `line` has `message` field, you will see `line.message` instead of whole `line._line`.

And in order to obtain the whole `line._line`, you can use `-j` option and `jq` to extract `_line` from each `line`.

So, I have to close this Pull Request without merging. I will let you know once the change gets merged.

Thanks!

**Comment by schans** [comment]
Sounds good. Thanks!

**Comment by smusali** [comment]
By the way, @schans, changes have already been added and updated!

**Comment by schans** [comment]
Awesome!

**Pull request closed without merging**
