### PR TITLE
Fixing the Issues and Updating CLI

### PR DESCRIPTION
**Pull request by smusali**
Changes include:
- Switching to use `tailserver` instead of `externalserver` for tailing;
- Fixing `params` field - renaming `query` into `q` - since `search` was not working at all with `query` - now it is working;
- Restructured the codebase;
- Removed `-f` and `-t` single-letter options; now we have only `--from` and `--to`;
- Added `-t`, `--tags` support for `tail` and `search` as requested in #17 ;
- Fixed `--from` and `--to` usage and added example for it as requested in #10 ;
- Using `(line.message || line._line)` in line rendering instead of just `line._line`; customers can use `-j` option in order to get the full line;
- Updated `README` and `--help` option output.

### CODE REVIEW

**Comment by respectus** [comment]
Code looks good, can we get a confirmation this works after testing? I'd be down to merge if we can get a confirmation

**Comment by smusali** [comment]
@respectus, you can pull the updates from this Pull Request and test it with just `node index.js search ...`. I tested `search` and it was working well. In the previous scenario, it wasn't working at all!

**Comment by smusali** [comment]
@respectus @leeliu, undone yet, I have some other things to add too.

**Comment by smusali** [comment]
@respectus, can you review it again? I have restructured some parts.

@leeliu, do you have any comments on this?

**Comment by smusali** [comment]
@leeliu @respectus Updated the description of this PR to - now this PR includes:
- Switching to use `tailserver` instead of `externalserver` for tailing;
- Fixing `params` field - renaming `query` into `q` - since `search` was not working at all with `query` - now it is working;
- Restructured the codebase;
- Removed `-f` and `-t` single-letter options; now we have only `--from` and `--to`;
- Added `-t`, `--tags` support for `tail` and `search` as requested in #17 ;
- Fixed `--from` and `--to` usage and added example for it as requested in #10 ;
- Using `(line.message || line._line)` in line rendering instead of just `line._line`; customers can use `-j` option in order to get the full line;
- Updated `README` and `--help` option output.

**Pull request merged**
